language: objective-c
osx_image: xcode7.1
sudo: false
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
script:
  - xctool -project Test.xcodeproj -scheme Test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project Test.xcodeproj -scheme Test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO