langure: objective-c
script:
  - xctool -project Test.xcodeproj -scheme Test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project Test.xcodeproj -scheme Test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO